// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Models;

public partial class Book
{
    [Key]
    [Column("BookID")]
    public int BookId { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string Title { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Author { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Genre { get; set; }

    [Column("No_Of_Copies")]
    public int? NoOfCopies { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<Checkout> Checkouts { get; set; } = new List<Checkout>();
}