// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Models;

public partial class Member
{
    [Key]
    [Column("MemberID")]
    public int MemberId { get; set; }

    [Required]
    [StringLength(40)]
    [Unicode(false)]
    public string FullName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column("member_type")]
    public bool? MemberType { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<Checkout> Checkouts { get; set; } = new List<Checkout>();
}