// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Models;

public partial class Penalty
{
    [Key]
    [Column("PenaltyID")]
    public int PenaltyId { get; set; }

    [Column("CheckOutID")]
    public int? CheckOutId { get; set; }

    [Column("Penalty_Amount")]
    public int? PenaltyAmount { get; set; }

    [Column("Paid_Status")]
    public bool PaidStatus { get; set; }

    [ForeignKey("CheckOutId")]
    [InverseProperty("Penalties")]
    public virtual Checkout CheckOut { get; set; }
}